'use client';

import { useEffect, useState, type SyntheticEvent } from 'react';
const api = process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:3333';
type User = { name: string; email: string; timezone: string };
type Session = { id: string; current: boolean; createdAt: string; expiresAt: string };

export function ProfilePanel() {
  const [user, setUser] = useState<User | null>(null); const [sessions, setSessions] = useState<Session[]>([]); const [csrf, setCsrf] = useState(''); const [message, setMessage] = useState('Carregando perfil…');
  async function load() { try { const response = await fetch(`${api}/v1/auth/session`, { credentials: 'include' }); if (!response.ok) { setMessage('Sua sessão expirou. Entre novamente.'); return; } const body = await response.json() as { data: { user: User; csrf: string } }; setUser(body.data.user); setCsrf(body.data.csrf); const list = await fetch(`${api}/v1/me/sessions`, { credentials: 'include' }); const result = await list.json() as { data: Session[] }; setSessions(result.data); setMessage(''); } catch { setMessage('Não foi possível carregar o perfil.'); } }
  useEffect(() => { void load(); }, []);
  async function mutation(path: string, method: string, body?: object) { const init: RequestInit = { method, credentials: 'include', headers: { 'Content-Type': 'application/json', 'X-CSRF-Token': csrf } }; if (body) init.body = JSON.stringify(body); const response = await fetch(`${api}${path}`, init); if (!response.ok) throw new Error(); return response; }
  async function save(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await mutation('/v1/me', 'PATCH', { name: data.get('name'), timezone: data.get('timezone') }); setMessage('Perfil salvo.'); await load(); } catch { setMessage('Não foi possível salvar o perfil.'); } }
  async function changePassword(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await mutation('/v1/me/change-password', 'POST', { currentPassword: data.get('currentPassword'), newPassword: data.get('newPassword') }); setMessage('Senha alterada. Entre novamente.'); } catch { setMessage('A senha atual não confere ou a nova senha é inválida.'); } }
  async function changeEmail(event: SyntheticEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { await mutation('/v1/me/change-email', 'POST', { password: data.get('password'), email: data.get('email') }); setMessage('E-mail alterado. Confirme o novo endereço e entre novamente.'); } catch { setMessage('Não foi possível alterar o e-mail.'); } }
  async function revoke(id: string) { try { await mutation(`/v1/me/sessions/${id}`, 'DELETE'); setSessions((items) => items.filter((item) => item.id !== id)); setMessage('Sessão encerrada.'); } catch { setMessage('Não foi possível encerrar a sessão.'); } }
  async function closeAccount() { if (!window.confirm('Encerrar sua conta? Esta ação remove o acesso e encerra todas as sessões.')) return; try { await mutation('/v1/me', 'DELETE'); window.location.assign('/entrar'); } catch { setMessage('Não foi possível encerrar a conta.'); } }
  if (!user) return <p role="status">{message}</p>;
  return <div className="profile-grid"><p role="status" aria-live="polite" className="full">{message}</p><form className="auth-form" onSubmit={(event) => { void save(event); }}><h2>Dados pessoais</h2><label htmlFor="profile-name">Nome</label><input id="profile-name" name="name" defaultValue={user.name} required /><label htmlFor="profile-email">E-mail</label><input id="profile-email" value={user.email} readOnly /><label htmlFor="timezone">Fuso horário</label><input id="timezone" name="timezone" defaultValue={user.timezone} required /><button>Salvar perfil</button></form><form className="auth-form" onSubmit={(event) => { void changePassword(event); }}><h2>Alterar senha</h2><label htmlFor="current-password">Senha atual</label><input id="current-password" name="currentPassword" type="password" autoComplete="current-password" required /><label htmlFor="new-password">Nova senha</label><input id="new-password" name="newPassword" type="password" autoComplete="new-password" minLength={10} required /><button>Alterar senha</button></form><form className="auth-form" onSubmit={(event) => { void changeEmail(event); }}><h2>Alterar e-mail</h2><label htmlFor="new-email">Novo e-mail</label><input id="new-email" name="email" type="email" autoComplete="email" required /><label htmlFor="email-password">Confirme sua senha</label><input id="email-password" name="password" type="password" autoComplete="current-password" required /><button>Alterar e-mail</button></form><section><h2>Encerrar conta</h2><p>O acesso será removido e todas as sessões serão encerradas.</p><button type="button" className="danger" onClick={() => { void closeAccount(); }}>Encerrar minha conta</button></section><section className="full"><h2>Sessões ativas</h2>{sessions.length === 0 ? <p>Nenhuma sessão ativa.</p> : <ul className="session-list">{sessions.map((session) => <li key={session.id}><span>{session.current ? 'Esta sessão' : `Iniciada em ${new Date(session.createdAt).toLocaleDateString('pt-BR')}`}</span><button type="button" onClick={() => { void revoke(session.id); }}>Encerrar</button></li>)}</ul>}</section></div>;
}
